version: "2"
volumes:
  db-data:
    externals: false

services:
  cache:
    image: memcached:1.4-alpine

  db:
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    image: postgres:9.5
    volumes:
      - db-data:/usr/local/pgsql/data

  jobs:
    env_file: .env 
    build: .
    volumes:
      - .:/usr/src/app
    command: bundle exec rake jobs:work
    depends_on:
      -db

  app:
    env_file: .env 
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    command: bundle exec rake jobs:work
    depends_on:
      -db